### ISSUE TITLE
Please, clarify the license on this package.

### ISSUE THREAD

**Issue by othyro** [txinto/redmine_startpage#15]
Greetings,

Could you please clarify the license on this package? I would like to import it to pkgsrc. It seems to work with redmine-3.0.3, BTW.

Best regards,

**Comment by txinto** [comment]
Hi, I've updated README to reflect the plugin is under GPLv2 license.

Best regards and thank you.

Tx

**Comment by othyro** [comment]
Thanks. This has been imported into pkgsrc as [devel/ruby-redmine_startpage](http://pkgsrc.se/devel/ruby-redmine_startpage).
